[tool.ruff]
line-length = 100
select = ["E", "F", "W", "I", "UP", "B"]
ignore = []
exclude = [".venv", "venv", "env", "build", "dist", "__pycache__"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto" 